# Generated by Django 5.1.4 on 2025-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("destination", models.CharField(max_length=30)),
                ("contact", models.IntegerField()),
            ],
        ),
    ]
