# Generated by Django 5.1.4 on 2025-01-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="destination",
            new_name="designation",
        ),
    ]
