# Generated by Django 5.1.4 on 2025-01-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("contact", models.IntegerField()),
            ],
            options={
                "db_table": "Customer",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("designation", models.CharField(max_length=30)),
                ("contact", models.IntegerField()),
            ],
            options={
                "db_table": "Employee",
            },
        ),
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "MyUser",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("contact", models.IntegerField()),
            ],
            options={
                "db_table": "Student",
            },
        ),
    ]
